# Generated by Django 5.2.6 on 2025-09-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите Ваш телеграм chat-id",
                max_length=55,
                null=True,
                verbose_name="Телеграм chat-id",
            ),
        ),
    ]
